# Generated by Django 4.2.18 on 2025-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
